# Build from sources for older architectures
name: fromSources

# Run this workflow manually from the Actions tab
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "populate"
  populate:
    # Run on a single platform or use a matrix to test against several
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        gr: [3.8.]
        bokeh: [2.0.2, 2.3.3]
      fail-fast: false
    env:
       TMPTMPDIR: /tmp
       
    # Steps represent a sequence of tasks that will be executed as part of the job
    name: gr-bokeh with gnuradio ${{ matrix.gr }} and bokeh ${{ matrix.bokeh }} on ${{ matrix.os }}
    steps:
      - name: Essential housekeeping
        run: |
          mkdir -p ~/artifacts
          sudo apt update
          
      - name: Security first
        if: true
        run: |
          sudo apt install -y software-properties-common apt-utils 
          sudo apt install -y unattended-upgrades
          sudo unattended-upgrade -d >~/artifacts/securityFirst.log

      - name: Performance second
        if: true
        run:  sudo apt upgrade -qy

      - name: Build essentials 
        if: true
        run: |
          sudo apt install -qy build-essential cmake cmake-curses-gui ninja-build
          sudo apt install -qy texinfo gawk g++ swig
          sudo apt install -qy npm nodejs
          sudo npm install -g npm@8.5
 
      - name: Other possible requirements (enable as needed)
        if: false
        run: |
          sudo apt install -qy build-essential npm nodejs cmake cmake-curses-gui ninja-build python3-pip
          sudo apt install -qy lrzip cmake g++ libboost-all-dev libgmp-dev swig python3-numpy \
                           python3-mako python3-sphinx python3-lxml doxygen libfftw3-dev \
                           libsdl1.2-dev libgsl-dev libqwt-qt5-dev libqt5opengl5-dev python3-pyqt5 \
                           liblog4cpp5-dev libzmq3-dev python3-yaml python3-click python3-click-plugins \
                           python3-zmq python3-scipy python3-gi python3-gi-cairo gir1.2-gtk-3.0 \
                           libcodec2-dev libgsm1-dev
          sudo apt install -qy pybind11-dev python3-matplotlib libsndfile1-dev \
                           python3-pip libsoapysdr-dev soapysdr-tools
          pip install pygccxml
          pip install pyqtgraph
          sudo apt install -qy libiio-dev libad9361-dev libspdlog-dev python3-packaging

      - name: Prefer Python 3
        if: true
        run: |
          sudo apt install -y python3-pip
          python3 -m pip install --user --upgrade pip
          pip install setuptools

      - name: MPIR 
        run: |
          sudo apt install -qy automake m4 yasm libtool
      

      - name: Install gnuradio
        run: |
          sudo apt install -qy libiio-dev libad9361-dev libspdlog-dev python3-packaging
          sudo apt install -qy liborc-dev

      
      - uses: actions/checkout@master

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gr=${{matrix.gr}}_bokeh=${{matrix.bokeh}}_os=${{matrix.os}}
          path: ~/artifacts/
