# This basic workflow can be invoked manually to help develop and test Actions

name: manual

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    branches: [ actions ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "populate"
  populate:
    # Run on a single platform or use a matrix to test against several
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.9'  ]
    env:
       MIRROR_ORG: nOw-Innovation
       
    # Steps represent a sequence of tasks that will be executed as part of the job
    name: gr-bokeh on ${{ matrix.os }} with python ${{ matrix.python-version }} 
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
       
      - name: Security first
        run: |
          sudo apt update
          sudo apt install -y unattended-upgrades
          sudo unattended-upgrade -d

      - name: Ensure thrid-party apt support is installed
        run: |
          sudo apt install -y software-properties-common apt-utils 
          if [ "${matrix.os} = "ubuntu-latest" ]; then
             sudo add-apt-repository -y ppa:gnuradio/gnuradio-releases-3.9
          fi
          sudo apt update


      - name: GNU ecosystem
        run: |
          sudo apt install -y python3-pip gnuradio gnuradio-dev
          pip install six
          gnuradio-config-info -v
          grcc -h

      # Run commands using the runners shell
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          echo $GITHUB_WORKSPACE
          pwd
          ls -l 
          echo Add other actions to build,test, and deploy your project.
