# Initial example courtesy https://dev.to/mihinduranasinghe/using-docker-containers-in-jobs-github-actions-3eof

name: noinstall

# Run this workflow manually from the Actions tab
on: workflow_dispatch


jobs:
  containerized:
    runs-on: ubuntu-latest
    env:
       TMPTMPDIR: /tmp
    container: 
       image: gnuradio:ubuntu-20.04-3.9
       env:
         TMPTMPDIR: /tmp
       
    # Steps represent a sequence of tasks that will be executed as part of the job
    name: Containerized execution
    steps:     
      - name: Make a place to store logs
        run: |
          mkdir -p ~/artifacts
          touch ~/artifacts/IAMImage.id
        
      - name: Upload artifacts from container?
        uses: actions/upload-artifact@v2
        with:
          name: container artifacts
          path: ~/artifacts/

  hosted:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    name: Hosted execution
    steps:     
    - name: Make a place to store logs
      run: |
        mkdir -p ~/artifacts
        touch ~/artifacts/IAMHost.id
        
    - name: Upload artifacts from host 
      uses: actions/upload-artifact@v2
      with:
        name: host artifacts
        path: ~/artifacts/
