# Initial example courtesy https://dev.to/mihinduranasinghe/using-docker-containers-in-jobs-github-actions-3eof

name: noinstall

# Run this workflow manually from the Actions tab
on: workflow_dispatch


jobs:
  containerized:
    name: Containerized execution
    runs-on: ubuntu-latest
    env:
       TMPTMPDIR: /tmp
    container: 
       image: ros:noetic-ros-core
       env:
         TMPTMPDIR: /tmp       
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:     
      - name: Make a place to store logs
        run: |
          mkdir -p ~/artifacts
          touch ~/artifacts/IAMImage.id

      - name: Test a command
        run: |
          whoami
          uname -a
          if ! $(which rosdep); then
             echo Not found
          fi

      - name: Upload artifacts from container?
        uses: actions/upload-artifact@v2
        with:
          name: container artifacts
          path: ~/artifacts/

  hosted:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    name: Hosted execution
    steps:     
    - name: Make a place to store logs
      run: |
        mkdir -p ~/artifacts
        touch ~/artifacts/IAMHost.id

    - name: Test a command
      run: |
        whoami
        uname -a
        if ! $(which rosdep); then
           echo Not found
        fi

    - name: Upload artifacts from host 
      uses: actions/upload-artifact@v2
      with:
        name: host artifacts
        path: ~/artifacts/
