# Build gr-bokehgui as an oot modules of gnuradio

name: radioconda

# Run this workflow manually from the Actions tab
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "populate"
  populate:
    # Run on a single platform or use a matrix to test against several
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [ '3.9'  ]
    env:
       TMPTMPDIR: /tmp
       OS_CHOICE: ${{ matrix.os }}
       
    # Steps represent a sequence of tasks that will be executed as part of the job
    name: gr-bokeh on ${{ matrix.os }} with python ${{ matrix.python-version }} 
    steps:       
      - name: Make a place to store artifacts
        run:  mkdir -p ~/artifacts

      - name: Security first
        run: |
          mkdir ~/logs
          sudo apt update
          sudo apt install -y software-properties-common apt-utils 2>~/artifacts/securityFirst.log >~/artifacts/securityFirst.log
          sudo apt install -y unattended-upgrades 2>>~/artifacts/securityFirst.log >>~/artifacts/securityFirst.log
          sudo unattended-upgrade -d 2>>~/artifacts/securityFirst.log >>~/artifacts/securityFirst.log

      - name: Ensure third-party apt support is installed
        run: |
          if [ "${OS_CHOICE}" = "ubuntu-latest" ]; then
             sudo add-apt-repository -y ppa:gnuradio/gnuradio-releases-3.9
          fi
          sudo apt update

      - name: radioconda
        run: |
          FILENAME="radioconda-2022.02.07-Linux-x86_64.sh"
          SHA256="f9a63e81d7ba581bfa2283b31259ecb7acd3e4647ac057ff84c828d400d91e84"
          echo "$SHA256 $FILENAME" >checksha.sha256
          wget -q https://github.com/ryanvolz/radioconda/releases/download/2022.02.07/$FILENAME
          sha256sum --check checksha.sha256 && bash $FILENAME -b
          eval "$(${HOME}/radioconda/bin/conda shell.bash hook)"
          TMPDIR=${TMPTMPDIR} conda init -q bash
          conda deactivate
          TMPDIR=${TMPTMPDIR} conda update -qy -c defaults conda
          exit

      - name: Install Bokeh and NodeJS and activate and upgrade radioconda
        run: |
          __conda_setup="$(~/radioconda/bin/conda shell.bash hook 2> /dev/null)"
          if [ $? -eq 0 ]; then
            eval "$__conda_setup"
          else
            if [ -f "~/radioconda/etc/profile.d/conda.sh" ]; then
              source "~/radioconda/etc/profile.d/conda.sh"
            else
              export PATH="~/radioconda/bin:$PATH"
            fi
          fi
          unset __conda_setup
          conda activate
          TMPDIR=${TMPTMPDIR} conda install -qy bokeh nodejs numpy scipy pandas
          TMPDIR=${TMPTMPDIR} conda upgrade --all
          bokeh info | tee ~/artifacts/bokeh.log
          python -m bokeh info  | tee -a ~/artifacts/bokeh.log
          
      - name: Checkout current branch
        uses: actions/checkout@master

      - name: Build gr-bokehgui using gr_modtool
        run: |
          __conda_setup="$(~/radioconda/bin/conda shell.bash hook 2> /dev/null)"
          if [ $? -eq 0 ]; then
            eval "$__conda_setup"
          else
            if [ -f "~/radioconda/etc/profile.d/conda.sh" ]; then
              source "~/radioconda/etc/profile.d/conda.sh"
            else
              export PATH="~/radioconda/bin:$PATH"
            fi
          fi
          unset __conda_setup
          conda activate
          echo TODO
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: log files
          path: ~/artifacts/
