# Rely on MiniConda to solve for dependencies and latest security updates
name: withConda

# Run this workflow manually from the Actions tab
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "populate"
  populate:
    # Run on a single platform or use a matrix to test against several
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        gr: [3.x.]
        bokeh: [2.x.]
      fail-fast: false
    env:
       TMPTMPDIR: /tmp
       
    # Steps represent a sequence of tasks that will be executed as part of the job
    name: gr-bokeh with gnuradio ${{ matrix.gr }} and bokeh ${{ matrix.bokeh }} on ${{ matrix.os }}
    steps:
      - name: Essential housekeeping
        run: |
          mkdir -p ~/artifacts
          sudo apt update
          
      - name: Security first
        if: true
        run: |
          sudo apt install -y software-properties-common apt-utils 
          sudo apt install -y unattended-upgrades
          sudo unattended-upgrade -d >~/artifacts/securityFirst.log

      - name: Performance second
        if: true
        run:  sudo apt upgrade -qy

      - name: Build essentials 
        if: true
        run: |
          sudo apt install -qy build-essential cmake cmake-curses-gui ninja-build
          sudo apt install -qy texinfo gawk g++ swig
          sudo apt install -qy npm nodejs
          sudo npm install -g npm@8.5
 
      - name: Install latest additional gnuradio dependencies 
        run: |
          sudo apt install -qy libiio-dev libad9361-dev libspdlog-dev python3-packaging
          sudo apt install -qy liborc-dev libfftw3-dev pybind11-dev libgmp-dev 

      - name: Prefer Python 3 when outside Conda
        if: true
        run: |
          sudo apt remove --purge python
          sudo apt install -y python-is-python3 python3-pip
          python3 -m pip install --user --upgrade pip
          pip install setuptools
          
      - name: Miniconda with mamba performance enhancements
        run: |
          FILENAME="Miniconda3-py39_4.10.3-Linux-x86_64.sh"
          SHA256="1ea2f885b4dbc3098662845560bc64271eb17085387a70c2ba3f29fff6f8d52f"
          echo "$SHA256 $FILENAME" >checksha.sha256
          wget https://repo.anaconda.com/miniconda/$FILENAME
          sha256sum --check checksha.sha256 && bash $FILENAME -b
          eval "$(${HOME}/miniconda3/bin/conda shell.bash hook)"
          TMPDIR=${TMPTMPDIR} conda init -q bash
          conda config --env --add channels conda-forge
          conda deactivate
          TMPDIR=${TMPTMPDIR} conda update -qy -c defaults conda
          conda install mamba -qy -n base -c conda-forge
          exit
  
      - uses: actions/checkout@master

      - name: Rely on mamba to install best version of gnuradio and bokeh
        run: |
          pushd ~
          __conda_setup="$(~/miniconda3/bin/conda shell.bash hook 2> /dev/null)"
          if [ $? -eq 0 ]; then
            eval "$__conda_setup"
          else
            if [ -f "~/miniconda3/etc/profile.d/conda.sh" ]; then
              source "~/miniconda3/etc/profile.d/conda.sh"
            else
              export PATH="~/miniconda3/bin:$PATH"
            fi
          fi
          unset __conda_setup
          conda activate
          popd
          TMPDIR=${TMPTMPDIR} mamba install -qy -c conda-forge gnuradio gnuradio-build-deps bokeh mpir
          
      - name: Build gr-bokehgui with CMake
        run: |
          pushd ~
          __conda_setup="$(~/miniconda3/bin/conda shell.bash hook 2> /dev/null)"
          if [ $? -eq 0 ]; then
            eval "$__conda_setup"
          else
            if [ -f "~/miniconda3/etc/profile.d/conda.sh" ]; then
              source "~/miniconda3/etc/profile.d/conda.sh"
            else
              export PATH="~/miniconda3/bin:$PATH"
            fi
          fi
          unset __conda_setup
          conda activate
          popd
          gnuradio-config-info --version  >~/artifacts/gnuradio.log
          gnuradio-config-info --prefix --prefs >>~/artifacts/gnuradio.log
          gnuradio-config-info --enabled-components >>~/artifacts/gnuradio.log
          gnuradio-config-info --cc --cxx --cflags >>~/artifacts/gnuradio.log
          python3 -m bokeh info >~/artifacts/bokeh.log
          TMPDIR=${TMPTMPDIR} mamba install -qy --only-deps -c rsarg gr-bokehgui
          mkdir -p build && cd build
          cmake -G Ninja -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_PREFIX_PATH=$CONDA_PREFIX -DLIB_SUFFIX="" ..
          cmake --build .
          sudo cmake --build . --target install
          
      - name: Did it work?
        run: |
          pushd ~
          __conda_setup="$(~/miniconda3/bin/conda shell.bash hook 2> /dev/null)"
          if [ $? -eq 0 ]; then
            eval "$__conda_setup"
          else
            if [ -f "~/miniconda3/etc/profile.d/conda.sh" ]; then
              source "~/miniconda3/etc/profile.d/conda.sh"
            else
              export PATH="~/miniconda3/bin:$PATH"
            fi
          fi
          unset __conda_setup
          conda activate
          popd
          cd examples
          grcc tutorial.grc
          cp tutorial.py ~/artifacts
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gr=${{matrix.gr}}_bokeh=${{matrix.bokeh}}_os=${{matrix.os}}
          path: ~/artifacts/
